#  filebrowser + qdirstat + apache + 
#  ps3netsrv

version: "3.6"
services:
  filebrowser:
    container_name: filebrowser-stack
    image: filebrowser/filebrowser:s6
    networks:
      MyMacvlan:
        ipv4_address: 10.10.20.150
    restart: unless-stopped
    environment:
      - PUID=0
      - PGID=0
      - UMASK=002
    volumes:
      - /srv/datastore/docker/filebrowser:/config
      - /srv/datastore/docker/filebrowser/database:/database
      - /srv:/srv
  
  qdirstat:
    container_name: qdirstat-stack
    image: linuxserver/qdirstat:latest
    networks:
      MyMacvlan:
        ipv4_address: 10.10.20.152
    ports:
      - 3000:3000/tcp
    restart: unless-stopped
    environment:
      - PUID=0
      - PGID=0
      - UMASK=002
    volumes:
      - /srv/datastore/docker/qdirstat/config:/config
      - /srv/mainpool:/data1
      - /srv/datastore:/data2

  apache-switch:
    command:
      - httpd-foreground
    container_name: apache-switch-stack
    environment:
      - HTTPD_PATCHES=
      - HTTPD_PREFIX=/usr/local/apache2
      - HTTPD_SHA256=eb397feeefccaf254f8d45de3768d9d68e8e73851c49afd5b7176d1ecf80c340
      - HTTPD_VERSION=2.4.54
      - PUID=0
      - PGID=0
      - UMASK=002
      - PATH=/usr/local/apache2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    hostname: 79aedd16b0dc
    image: httpd:2.4
    networks:
      MyMacvlan:
        ipv4_address: 10.10.20.154
    ports:
      - 8080:80/tcp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /srv/mainpool/media/switch:/usr/local/apache2/htdocs
    working_dir: /usr/local/apache2


  ps3netsrv:
    image: shawly/ps3netsrv
    container_name: ps3netsrv
    networks: 
      MyMacvlan:
        ipv4_address: 10.10.20.50
    environment:
      - TZ=America/Toronto 
      - PUID=0
      - GUID=0
    volumes:
      - /srv/mainpool/media/ps3:/games




networks:
  MyMacvlan:
    external: true
    name: MyMacvlan
